#!/bin/sh
brew install composer
brew install coreutils
brew install exa
brew install fzf
brew install git
brew install gnupg
brew install mas
brew install nodebrew
brew install postgresql
brew install wget
brew install zsh
brew install zsh-syntax-highlighting
