#!/bin/sh
brew cask install alfred
brew cask install appcleaner
brew cask install bettertouchtool
brew cask install diskwave
brew cask install google-chrome
brew cask install hyperswitch
brew cask install iterm2
brew cask install keka
brew cask install onyx
brew cask install phpstorm
brew cask install vagrant
brew cask install virtualbox
brew cask install webstorm
