#!/bin/sh
brew install ansible
brew install composer
brew install coreutils
brew install exa
brew install fzf
brew install git
brew install git-secrets
brew install gnupg
brew install mas
brew install nodebrew
brew install php
brew install postgresql
brew install wget
brew install zsh
brew install zsh-syntax-highlighting
